### ISSUE TITLE
Question on event start time 

### ISSUE THREAD

**Issue by TJUZMX** [jpjones76/STA-LTA-OS#1] opened 2019-01-06 03:04 UTC
Hello
    I'm a beginner in signal processing. I want to obtain the start time of transient signal. I use the command Ev = hmmscan(X); But Ev doesn't contain Ev.s. What caused this ? Here is the test data.
                                                                                                      Any suggestions are gratefully accepted. 
[transient signal data.txt](https://github.com/jpjones76/STA-LTA-OS/files/2730101/transient.signal.data.txt)

**Comment by jpjones76** [comment] 2019-01-06 06:30
If Ev contains no .s field, then no events are detected. It appears that you're feeding in a raw (untransformed) time series to hmmscan. You need to either transform x(t) or choose a PDF type so that the domain of the (transformed) input matches the range of the PDFs. For example, if you're using exponential distributions in the HMM, you should input either the absolute value or the envelope of x(t); if you want to keep using the raw time series, use Gaussians in the HMM.

**Comment by jpjones76** [comment] 2019-01-08 21:25
Can you please confirm that transforming X or changing the PDF shape fixes your issue? I'd like to close this. Thanks.

**Comment by TJUZMX** [comment] 2019-01-09 02:11
Sorry for not replying to your message in time. I have transformed X and changed the PDF shape.  But Ev still contains no .s field. Can it be caused by the unreasonable setting of options?. Because I don't understand the principle thoroughly enough, I think it may take me more time to solve this problem.

**Comment by jpjones76** [comment] 2019-01-09 09:43
How many data channels are you using when you run the algorithm?

**Comment by TJUZMX** [comment] 2019-01-09 13:18
I use the default 6 channels in function hmmscan. Although I have changed it from 1to 20, there is still no ,s field. The waveform of raw data is similar to the shape shown in this image. Could you please help me extract the start time of the signal in the .txt file?  I shall be very grateful.
![image](https://user-images.githubusercontent.com/32473769/50901360-eac28080-1452-11e9-96b0-10e62c0d6f45.png)
[signal data.txt](https://github.com/jpjones76/STA-LTA-OS/files/2741031/signal.data.txt)

**Comment by jpjones76** [comment] 2019-01-10 08:37
Please paste a minimum working example of the command sequence that you use to run hmmscan, beginning with reading your data into Matlab and including preprocessing commands. Please also include basic information about the data set, like the number of data channels that you're using.

**Comment by TJUZMX** [comment] 2019-01-10 13:25
Here is the Matlab code. When I change the channels into 0, Ev.s field appeared. Is this a reasonable phenomenon?
Then I compare the calculated start time with manually marked start time. The result is not as expected. Can I obtain a better result by parameter optimization？I paste some wave data in .ZIP
 file, they are all in txt format. All signals are ultrasound signals. 
Thank you very much for taking so long time to answer my question.

%% II. Import data
fileFolder=fullfile('E:\Postgraduate\DATA'); 
dirOutput=dir(fullfile(fileFolder,'*.txt'));
fileNames={dirOutput.name}'; 

for i = 1:length(fileNames)
    fin = fopen(fileNames{i},'r');
    waveheader = fgetl(fin);
    fclose(fin);
    % Obtain the manually marked onset position of the signal
    endchar = length(waveheader);
    startpoint(i) = str2double(waveheader(5:endchar));
    % Import waveform data
    wave(:,i) = textread(fileNames{i},'','headerlines',1); 
    
    Ev{i} = hmmscan(wave(1:2000,i),'Lw',300,'Sw',200,'s0',0,'fs',2500000);
    startpoint_pre(i)=Ev{i}.s(1)*2500000;
end
figure(1)
plot(startpoint,'k')
hold on 
plot(startpoint_pre,'r')

[wavedata.zip](https://github.com/jpjones76/STA-LTA-OS/files/2745441/wavedata.zip)

**Comment by jpjones76** [comment] 2019-01-11 06:31
Potential isssues:
1. `hmmscan` should use all channels simultaneously. It assumes channel data are synchronized in time, sampled at a uniform fs, and the same length. So, the call to `hmmscan` shouldn't be in the channel loop.
1. f0 = 0.10 is too low for this example. From the plots, most of the time series is signal. What happens if f0 = 0.7 and fw = [0.5 0.9]?
1. Any STA-LTA algorithm should have `Lw >= 2*Sw`.
   1. In Rex Allen's original STA-LTA code, Earthworm, and probably Antelope, `Lw = 8*Sw`. 
   1. Typically in exploration seismology `2*Sw <= Lw <= 4*Sw`. 
   1. I recommend `Lw >= 5*Sw` here, because the HMM is re-evaluated every `Lw` samples. 

Try this, instead:
```Matlab
fs = 4000;                                         % Change as needed; specify in Hz
Nf = length(fileNames);
Nx = 2000;
wave = zeros([Nx Nf]);
for i = 1:Nf
  fin = fopen(fileNames{i},'r');
  waveheader = fgetl(fin);
  fclose(fin);
  x = textread(fileNames{i},'','headerlines',1);
  wave(:,i) = x(1:Nx);
end
Ev = hmmscan(wave, 'Lw', 1000, 'Sw', 100, 'fs', fs, 'f0', 0.7, 'fw', [0.5 0.9]);
```

A minor issue that will affect the absolute pick times is that fs should be in Hz. I suspect your seismic data wasn't sampled at 2.5 MHz...probably something like 4000 Hz, right?

**Comment by TJUZMX** [comment] 2019-01-12 02:59
Thanks very much for your careful and patient answers. I will try to optimize the results according to your suggestions.

**Comment by jpjones76** [comment] 2019-01-12 11:05
OK. I'm going to close this issue now, since it doesn't seem to be caused by a bug in the code. Thank you for your questions.

It's clear that I could have done a much better job with my documentation, though. I'll try to work on that over the weekend.

**Closed as completed by jpjones76** 2019-01-12 11:05 UTC
